server:
  port: 8082

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/timestamp_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: homestead
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
